#- Generated by update.raku
#- Based on Release 20198 - 2019-03-25 22:01:33 -0700

use DateTime::TimeZone::Zone;

class DateTime::TimeZone::Zone::Pacific::Funafuti
  does DateTime::TimeZone::Zone
{
    method name(--> 'Pacific/Funafuti') { }

    method zonedata() {
        BEGIN Map.new((:baseoffset("11:56:52"),:until(-2177452800))), Map.new((:baseoffset("12:00")))
    }

    method rules() {
        BEGIN Map.new
    }
}
