#- Generated by parse.raku
#- Based on Release 20198 - 2019-03-25 22:01:33 -0700

use DateTime::TimeZone::Zone;

class DateTime::TimeZone::Zone::Pacific::Palau
  does DateTime::TimeZone::Zone
{
    method name(--> 'Pacific/Palau') { }

    method zonedata() {
        BEGIN Map.new((:baseoffset("-15:02:04"),:until(-3944678400))), Map.new((:baseoffset("8:57:56"),:until(-2177452800))), Map.new((:baseoffset("9:00")))
    }

    method rules() {
        BEGIN Map.new
    }
}
